import type {GetStaticProps, InferGetStaticPropsType, NextPage} from 'next'
import Head from 'next/head'
import axios from 'axios';
import formatDate from 'date-fns/format';
import addSeconds from 'date-fns/addSeconds';

import styles from '../styles/Home.module.css'


type Props = {
  text: string;
  generatedAt: string;
  nextUpdateAt: string;
};

const dateFormat = 'dd.MM.yyyy HH:mm:ss';

export const getStaticProps: GetStaticProps<Props> = async () => {
  const response = await axios.get<string[]>('https://baconipsum.com/api/?type=meat-and-filler');
  const [ text ] = await response.data;
  const now = new Date();

  const generatedAt = formatDate(now, dateFormat);
  const nextUpdateAt = formatDate(addSeconds(now, 10), dateFormat);

  return {
    props: { text, generatedAt, nextUpdateAt },
    revalidate: 10,
  }
}

function Home({ text, generatedAt, nextUpdateAt }: InferGetStaticPropsType<typeof getStaticProps>) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Test server side článku</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Článek
        </h1>

        <h3>Článek načten v {generatedAt}</h3>

        <p>Další načtení článku na API proběhne v {nextUpdateAt}</p>

        <p>{text}</p>

      </main>
    </div>
  )
}

export default Home
